### PR TITLE
add stop button

### PR DESCRIPTION
**Pull request by zainbinfurqan**
i have added a stop button

### CODE REVIEW

**Comment by zainbinfurqan** [comment]
#5 i have added stop button

**Comment by NetStorm84** [comment]
Could we make it so that the Start Button becomes the Stop button, so there is only one button visible? Then I will merge.

**Comment by zainbinfurqan** [comment]
ok i ll do it

**Comment by zainbinfurqan** [comment]
done @NetStorm84  please merge

**Comment by zainbinfurqan** [comment]
did you merge my PR? @NetStorm84

**Comment by zainbinfurqan** [comment]
didn't you merge my PR?

**Pull request closed without merging**
